INSERT INTO currency_lk (name, code, description, created_on)
 VALUES
('AED', 'AED', 'United Arab Emirates Dirham', current_timestamp),
('AFN', 'AFN', 'Afghan Afghani', current_timestamp),
('ALL', 'ALL', 'Albanian Lek', current_timestamp),
('AMD', 'AMD', 'Armenian Dram', current_timestamp),
('ANG', 'ANG', 'Netherlands Antillean Guilder', current_timestamp),
('AOA', 'AOA', 'Angolan Kwanza', current_timestamp),
('ARS', 'ARS', 'Argentine Peso', current_timestamp),
('AUD', 'AUD', 'Australian Dollar', current_timestamp),
('AWG', 'AWG', 'Aruban Florin', current_timestamp),
('AZN', 'AZN', 'Azerbaijani Manat', current_timestamp),
('BAM', 'BAM', 'Bosnia-Herzegovina Convertible Mark', current_timestamp),
('BBD', 'BBD', 'Barbadian Dollar', current_timestamp),
('BDT', 'BDT', 'Bangladeshi Taka', current_timestamp),
('BGN', 'BGN', 'Bulgarian Lev', current_timestamp),
('BHD', 'BHD', 'Bahraini Dinar', current_timestamp),
('BIF', 'BIF', 'Burundian Franc', current_timestamp),
('BMD', 'BMD', 'Bermudian Dollar', current_timestamp),
('BND', 'BND', 'Brunei Dollar', current_timestamp),
('BOB', 'BOB', 'Bolivian Boliviano', current_timestamp),
('BRL', 'BRL', 'Brazilian Real', current_timestamp),
('BSD', 'BSD', 'Bahamian Dollar', current_timestamp),
('BTN', 'BTN', 'Bhutanese Ngultrum', current_timestamp),
('BWP', 'BWP', 'Botswanan Pula', current_timestamp),
('BYN', 'BYN', 'Belarusian Ruble', current_timestamp),
('BZD', 'BZD', 'Belize Dollar', current_timestamp),
('CAD', 'CAD', 'Canadian Dollar', current_timestamp),
('CDF', 'CDF', 'Congolese Franc', current_timestamp),
('CHF', 'CHF', 'Swiss Franc', current_timestamp),
('CLP', 'CLP', 'Chilean Peso', current_timestamp),
('CNY', 'CNY', 'Chinese Yuan', current_timestamp),
('COP', 'COP', 'Colombian Peso', current_timestamp),
('CRC', 'CRC', 'Costa Rican Colón', current_timestamp),
('CUP', 'CUP', 'Cuban Peso', current_timestamp),
('CVE', 'CVE', 'Cape Verdean Escudo', current_timestamp),
('CZK', 'CZK', 'Czech Koruna', current_timestamp),
('DJF', 'DJF', 'Djiboutian Franc', current_timestamp),
('DKK', 'DKK', 'Danish Krone', current_timestamp),
('DOP', 'DOP', 'Dominican Peso', current_timestamp),
('DZD', 'DZD', 'Algerian Dinar', current_timestamp),
('EGP', 'EGP', 'Egyptian Pound', current_timestamp),
('ERN', 'ERN', 'Eritrean Nakfa', current_timestamp),
('ETB', 'ETB', 'Ethiopian Birr', current_timestamp),
('EUR', 'EUR', 'Euro', current_timestamp),
('FJD', 'FJD', 'Fijian Dollar', current_timestamp),
('FKP', 'FKP', 'Falkland Islands Pound', current_timestamp),
('FOK', 'FOK', 'Faroese Króna', current_timestamp),
('GBP', 'GBP', 'British Pound Sterling', current_timestamp),
('GEL', 'GEL', 'Georgian Lari', current_timestamp),
('GGP', 'GGP', 'Guernsey Pound', current_timestamp),
('GHS', 'GHS', 'Ghanaian Cedi', current_timestamp),
('GIP', 'GIP', 'Gibraltar Pound', current_timestamp),
('GMD', 'GMD', 'Gambian Dalasi', current_timestamp),
('GNF', 'GNF', 'Guinean Franc', current_timestamp),
('GTQ', 'GTQ', 'Guatemalan Quetzal', current_timestamp),
('GYD', 'GYD', 'Guyanese Dollar', current_timestamp),
('HKD', 'HKD', 'Hong Kong Dollar', current_timestamp),
('HNL', 'HNL', 'Honduran Lempira', current_timestamp),
('HRK', 'HRK', 'Croatian Kuna', current_timestamp),
('HTG', 'HTG', 'Haitian Gourde', current_timestamp),
('HUF', 'HUF', 'Hungarian Forint', current_timestamp),
('IDR', 'IDR', 'Indonesian Rupiah', current_timestamp),
('ILS', 'ILS', 'Israeli New Shekel', current_timestamp),
('IMP', 'IMP', 'Isle of Man Pound', current_timestamp),
('INR', 'INR', 'Indian Rupee', current_timestamp),
('IQD', 'IQD', 'Iraqi Dinar', current_timestamp),
('IRR', 'IRR', 'Iranian Rial', current_timestamp),
('ISK', 'ISK', 'Icelandic Króna', current_timestamp),
('JEP', 'JEP', 'Jersey Pound', current_timestamp),
('JMD', 'JMD', 'Jamaican Dollar', current_timestamp),
('JOD', 'JOD', 'Jordanian Dinar', current_timestamp),
('JPY', 'JPY', 'Japanese Yen', current_timestamp),
('KES', 'KES', 'Kenyan Shilling', current_timestamp),
('KGS', 'KGS', 'Kyrgyzstani Som', current_timestamp),
('KHR', 'KHR', 'Cambodian Riel', current_timestamp),
('KID', 'KID', 'Kiribati Dollar', current_timestamp),
('KMF', 'KMF', 'Comorian Franc', current_timestamp),
('KRW', 'KRW', 'South Korean Won', current_timestamp),
('KWD', 'KWD', 'Kuwaiti Dinar', current_timestamp),
('KYD', 'KYD', 'Cayman Islands Dollar', current_timestamp),
('KZT', 'KZT', 'Kazakhstani Tenge', current_timestamp),
('LAK', 'LAK', 'Lao Kip', current_timestamp),
('LBP', 'LBP', 'Lebanese Pound', current_timestamp),
('LKR', 'LKR', 'Sri Lankan Rupee', current_timestamp),
('LRD', 'LRD', 'Liberian Dollar', current_timestamp),
('LSL', 'LSL', 'Lesotho Loti', current_timestamp),
('LYD', 'LYD', 'Libyan Dinar', current_timestamp),
('MAD', 'MAD', 'Moroccan Dirham', current_timestamp),
('MDL', 'MDL', 'Moldovan Leu', current_timestamp),
('MGA', 'MGA', 'Malagasy Ariary', current_timestamp),
('MKD', 'MKD', 'Macedonian Denar', current_timestamp),
('MMK', 'MMK', 'Myanmar Kyat', current_timestamp),
('MNT', 'MNT', 'Mongolian Tögrög', current_timestamp),
('MOP', 'MOP', 'Macanese Pataca', current_timestamp),
('MRU', 'MRU', 'Mauritanian Ouguiya', current_timestamp),
('MUR', 'MUR', 'Mauritian Rupee', current_timestamp),
('MVR', 'MVR', 'Maldivian Rufiyaa', current_timestamp),
('MWK', 'MWK', 'Malawian Kwacha', current_timestamp),
('MXN', 'MXN', 'Mexican Peso', current_timestamp),
('MYR', 'MYR', 'Malaysian Ringgit', current_timestamp),
('MZN', 'MZN', 'Mozambican Metical', current_timestamp),
('NAD', 'NAD', 'Namibian Dollar', current_timestamp),
('NGN', 'NGN', 'Nigerian Naira', current_timestamp),
('NIO', 'NIO', 'Nicaraguan Córdoba', current_timestamp),
('NOK', 'NOK', 'Norwegian Krone', current_timestamp),
('NPR', 'NPR', 'Nepalese Rupee', current_timestamp),
('NZD', 'NZD', 'New Zealand Dollar', current_timestamp),
('OMR', 'OMR', 'Omani Rial', current_timestamp),
('PAB', 'PAB', 'Panamanian Balboa', current_timestamp),
('PEN', 'PEN', 'Peruvian Sol', current_timestamp),
('PGK', 'PGK', 'Papua New Guinean Kina', current_timestamp),
('PHP', 'PHP', 'Philippine Peso', current_timestamp),
('PKR', 'PKR', 'Pakistani Rupee', current_timestamp),
('PLN', 'PLN', 'Polish Złoty', current_timestamp),
('PYG', 'PYG', 'Paraguayan Guaraní', current_timestamp),
('QAR', 'QAR', 'Qatari Riyal', current_timestamp),
('RON', 'RON', 'Romanian Leu', current_timestamp),
('RSD', 'RSD', 'Serbian Dinar', current_timestamp),
('RUB', 'RUB', 'Russian Ruble', current_timestamp),
('RWF', 'RWF', 'Rwandan Franc', current_timestamp),
('SAR', 'SAR', 'Saudi Riyal', current_timestamp),
('SBD', 'SBD', 'Solomon Islands Dollar', current_timestamp),
('SCR', 'SCR', 'Seychellois Rupee', current_timestamp),
('SDG', 'SDG', 'Sudanese Pound', current_timestamp),
('SEK', 'SEK', 'Swedish Krona', current_timestamp),
('SGD', 'SGD', 'Singapore Dollar', current_timestamp),
('SHP', 'SHP', 'Saint Helena Pound', current_timestamp),
('SLE', 'SLE', 'Sierra Leonean Leone', current_timestamp),
('SOS', 'SOS', 'Somali Shilling', current_timestamp),
('SRD', 'SRD', 'Surinamese Dollar', current_timestamp),
('SSP', 'SSP', 'South Sudanese Pound', current_timestamp),
('STN', 'STN', 'São Tomé and Príncipe Dobra', current_timestamp),
('SYP', 'SYP', 'Syrian Pound', current_timestamp),
('SZL', 'SZL', 'Eswatini Lilangeni', current_timestamp),
('THB', 'THB', 'Thai Baht', current_timestamp),
('TJS', 'TJS', 'Tajikistani Somoni', current_timestamp),
('TMT', 'TMT', 'Turkmenistani Manat', current_timestamp),
('TND', 'TND', 'Tunisian Dinar', current_timestamp),
('TOP', 'TOP', 'Tongan Paʻanga', current_timestamp),
('TRY', 'TRY', 'Turkish Lira', current_timestamp),
('TTD', 'TTD', 'Trinidad and Tobago Dollar', current_timestamp),
('TVD', 'TVD', 'Tuvaluan Dollar', current_timestamp),
('TWD', 'TWD', 'New Taiwan Dollar', current_timestamp),
('TZS', 'TZS', 'Tanzanian Shilling', current_timestamp),
('UAH', 'UAH', 'Ukrainian Hryvnia', current_timestamp),
('UGX', 'UGX', 'Ugandan Shilling', current_timestamp),
('USD', 'USD', 'United States Dollar', current_timestamp),
('UYU', 'UYU', 'Uruguayan Peso', current_timestamp),
('UZS', 'UZS', 'Uzbekistani Soʻm', current_timestamp),
('VES', 'VES', 'Venezuelan Bolívar Soberano', current_timestamp),
('VND', 'VND', 'Vietnamese Đồng', current_timestamp),
('VUV', 'VUV', 'Vanuatu Vatu', current_timestamp),
('WST', 'WST', 'Samoan Tālā', current_timestamp),
('XAF', 'XAF', 'Central African CFA Franc', current_timestamp),
('XCD', 'XCD', 'East Caribbean Dollar', current_timestamp),
('XOF', 'XOF', 'West African CFA Franc', current_timestamp),
('XPF', 'XPF', 'CFP Franc', current_timestamp),
('YER', 'YER', 'Yemeni Rial', current_timestamp),
('ZAR', 'ZAR', 'South African Rand', current_timestamp),
('ZMW', 'ZMW', 'Zambian Kwacha', current_timestamp),
('ZWL', 'ZWL', 'Zimbabwean Dollar', current_timestamp);